### ISSUE TITLE
Error, can help?

### ISSUE THREAD

**Issue by f8er4g8ergerg4e87ezrze5r4z8r7z** [shrey-bansal/ABINBEV#1]
INVOICE-SCANNER]$ python app.py 
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from crnn_processor import get_html
  File "/var/www/html/INVOICE-SCANNER/backend/ReceiptGenerator/crnn_processor.py", line 71, in <module>
    from veryfi import Client
ModuleNotFoundError: No module named 'veryfi'

**Comment by juvebogdan** [comment]
This repo is not using depp learning model. It just uses commercial tool veryfi
